python -m baselines.autospec.run \
    --name fb_run \
    --input /home/mdrh/code/specsyns/benchmarks/formalbench/fb.json \
    --output /home/mdrh/experiments/exp-results/fb \
    --openjml_timeout 300 \
    --threads 8 \
    --verbose \
    --model gpt-4o \
    --temperature 0.7 \
    --prompt_type zero_shot \
    --max_iterations 10