python -m baselines.formalbench.run \
    --name sgb_run \
    --input /home/mdrh/code/specsyns/benchmarks/specgenbench/sgb.json \
    --output /home/mdrh/experiments/output \
    --openjml_timeout 300 \
    --threads 4 \
    --verbose \
    --model gpt-4o \
    --temperature 0.7 \
    --prompt_type zero_shot \
    --max_iterations 10 \
    --strict
