python -m baselines.specgen.run \
    --name fb_run \
    --input /home/mdrh/code/specsyns/benchmarks/formalbench/fb.json \
    --output /home/mdrh/experiments/exp-results/fb \
    --openjml_timeout 300 \
    --threads 5 \
    --verbose \
    --model gemini-2.5-flash \
    --temperature 0.7 \
    --prompt_type zero_shot \
    --max_iterations 10