python -m baselines.specgen.run \
    --name fb_run \
    --input /home/mdrh/code/specsyns/benchmarks/formalbench/fb.json \
    --output /home/mdrh/experiments/exp-results/formalbench \
    --openjml_timeout 300 \
    --threads 4 \
    --verbose \
    --model gpt-4o-2024-08-06 \
    --temperature 0.7 \
    --prompt_type two_shot \
    --max_iterations 10